# Generated by Django 3.2.4 on 2021-06-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
