# Generated by Django 3.2.4 on 2021-06-27 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0007_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_request',
            field=models.ManyToManyField(blank=True, related_name='friend_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
