# Generated by Django 3.2.4 on 2021-07-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='place',
        ),
        migrations.RemoveField(
            model_name='work',
            name='date',
        ),
        migrations.RemoveField(
            model_name='work',
            name='place',
        ),
        migrations.AddField(
            model_name='education',
            name='education_date',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='education',
            name='education_place',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='work',
            name='work_date',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='work',
            name='work_place',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
