# Generated by Django 3.2.4 on 2021-07-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20210703_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.profile'),
        ),
        migrations.AlterField(
            model_name='work',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.profile'),
        ),
    ]
